name: Python Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: jrottenberg/ffmpeg:7.1-ubuntu2404-edge

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run ruff
        run: uv run ruff check .

      - name: Run ruff format check
        run: uv run ruff format --check

      - name: Type check with mypy
        run: uv run mypy . --strict --ignore-missing-imports

      - name: Run tests
        run: uv run pytest
